In [28]:
import numpy as np
arr1 = np.array([[6, 28, 19, 14, 20, 19, 18], [19, 16, 17, 20, 18, 20, 17], [23, 22, 89, 78, 28, 19, 10]])

np.where(arr1 == [])

array([16.        , 22.        , 41.66666667, 37.33333333, 22.        ,
       19.33333333, 15.        ])

In [21]:
b = [6, 28, 19, 14, 20, 19, 18, 19, 16, 17, 20, 18, 20]

print(b.index(19, 5))

5


In [19]:
list(arr1).index(28)

1

In [22]:
arr1[[2,3,5]]

array([19, 14, 19])

In [37]:
arr2 = np.array([6, 28, 19, 14, 20, 19, 18, 19, 16, 17, 20, 18, 20, 17, 23, 22, 89, 78, 28, 19, 10])
arr2[arr2 == 19]

array([19, 19, 19, 19])

In [38]:
arr1


array([[ 6, 28, 19, 14, 20, 19, 18],
       [19, 16, 17, 20, 18, 20, 17],
       [23, 22, 89, 78, 28, 19, 10]])

In [44]:
print(arr1.max)

<built-in method max of numpy.ndarray object at 0x73872c103b20>
