In [1]:
import numpy as np

arr1 = np.array([[6, 9 , 19, 17], [8, 28, 19, 17], [17, 18, 28, 90]])
arr1.mean(0)

array([10.33333333, 18.33333333, 22.        , 41.33333333])

In [2]:
arr1.mean(1)

array([12.75, 18.  , 38.25])

In [3]:
arr1.mean()

23.0

In [7]:
np.mean(arr1, 0)
arr1.var(0)

array([  22.88888889,   60.22222222,   18.        , 1184.22222222])

In [28]:
y = np.array([1, 1, 1,  1, 0,  0, 1, 0])

p = np.array([False, True, False, True, True, True, False, True])
print(p)
p.not



[False  True False  True False False False False]


5

In [14]:
y = np.array([1, 1, 1,  1, 0,  0, 1, 0])

p = np.array([0, 1, 0, 1, 1, 1, 0, 1])

y[p]

array([1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.bool(p)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()